version: '3.8'

services:
  web-php:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      DB_HOST: db
      DB_NAME: phpdb
      DB_USER: phpuser
      DB_PASS: phppass
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: phpdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpdb
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: phppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: phpuser
      PMA_PASSWORD: phppass
    depends_on:
      - db

volumes:
  db_data:
